// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0UmjM5qDfmCP_56aCN4R9c4Xnog4klJI',
    appId: '1:236765072827:web:901a1341f4ef0d3598889e',
    messagingSenderId: '236765072827',
    projectId: 'stock-market-27667',
    authDomain: 'stock-market-27667.firebaseapp.com',
    storageBucket: 'stock-market-27667.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcwbvjKijlVJTQ0w-2Dz3Lkwqmkm69mJY',
    appId: '1:236765072827:android:cfa4d5d8e74536a298889e',
    messagingSenderId: '236765072827',
    projectId: 'stock-market-27667',
    storageBucket: 'stock-market-27667.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrThd0cKc3nhbRnHpBXtEvKiNpdoDIBeI',
    appId: '1:236765072827:ios:b578258a9a568fef98889e',
    messagingSenderId: '236765072827',
    projectId: 'stock-market-27667',
    storageBucket: 'stock-market-27667.appspot.com',
    iosClientId: '236765072827-rrf628k14vijcpl5pam50kgco0r8d3ab.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrThd0cKc3nhbRnHpBXtEvKiNpdoDIBeI',
    appId: '1:236765072827:ios:3dd4eefdc85a4a7c98889e',
    messagingSenderId: '236765072827',
    projectId: 'stock-market-27667',
    storageBucket: 'stock-market-27667.appspot.com',
    iosClientId: '236765072827-nl124h8t04mhkaloq6btsejft10dljau.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockMarket.RunnerTests',
  );
}
